version: "3.8"

services:
  db:
    image: postgres
    restart: always
    container_name: postgres-meal-planner
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
